#NUMPY TUTORIAL

In [1]:
import numpy as np

array from python structures

In [2]:
#creating array from list
myarr=np.array([[3,6,37,7]])
myarr

array([[ 3,  6, 37,  7]])

In [3]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int32')

In [5]:
myarr[0,1]

6

In [6]:
myarr[0,1]=45
myarr

array([[ 3, 45, 37,  7]])

In [7]:
#creating array from dictionary
myar=np.array({3,6,37,7})
myar


array({3, 37, 6, 7}, dtype=object)

numpy array creation objects

In [9]:
zeros=np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
rng=np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
#10 linearly spaced elements from 1 to 50
lspace=np.linspace(1,50,10)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [12]:
#array with random elements
emp=np.empty((4,6))
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.15711786e-306, 1.89146896e-307, 7.56571288e-307],
       [4.00544531e-307, 1.11261095e-306, 3.56043054e-307,
        1.37961641e-306, 2.22518251e-306, 1.33511969e-306],
       [6.23036978e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 2.22522597e-306, 1.33511290e-306],
       [1.69118108e-306, 9.34604358e-307, 9.34598925e-307,
        1.24612081e-306, 2.22522596e-306, 2.22507386e-306]])

In [13]:
emp_like=np.empty_like(lspace)
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [14]:
#indentity matrix
ide=np.identity(45)
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [15]:
arr=np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [18]:
arr=arr.reshape(3,33)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [19]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr.shape

(3, 33)

# numpy axis
1D->axis 0
2D->axis 1(spans rows),axis 0(spans columns)

In [22]:
ar=np.array([[1,2,3],[4,5,6],[7,1,0]])
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [23]:
ar.sum(axis=0)

array([12,  8,  9])

In [24]:
ar.sum(axis=1)

array([ 6, 15,  8])

# Numpy Attributes

In [25]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [26]:
#iterator
ar.flat

In [27]:
#dimension
ar.ndim

2

In [28]:
ar.size

9

In [29]:
ar.nbytes

36

# Numpy Methods

In [30]:
one=np.array([1,3,4,634,2])
#index of max element
one.argmax()

3

In [31]:
one.argmin()

0

In [32]:
one.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [35]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [ ]:
ar.argmin()

In [36]:
ar.argmax()

6

In [37]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [38]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [39]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [40]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [41]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [42]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

# Numpy Operations

In [46]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [44]:
ar2=np.array([[1,2,1],[4,0,6],[8,1,0]])
ar2

array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [45]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [47]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [48]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [49]:
ar.max()

7

In [50]:
ar.min()

0

In [51]:
ar.sum()

29

In [52]:
np.where(ar>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [53]:
type(np.where(ar>5))

tuple

In [54]:
np.count_nonzero(ar)

8

In [55]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

# Why we use numpy? Beacuse it takes less size.
PROOF:-

In [56]:
import sys

In [59]:
x=[0,4,55,2]
np_ar=np.array(x)
np_ar

array([ 0,  4, 55,  2])

In [60]:
sys.getsizeof(1)*len(x)

112

In [61]:
np_ar.itemsize*np_ar.size

16